### ISSUE TITLE
Cast bars absent during the Lord Valthalak encounter 

### ISSUE THREAD

**Issue by GHuser12** [wardz/ClassicCastbars#59]
**Is your feature request related to a problem?**

The Dungeon 2.0 questline ends with a boss battle in Upper Blackrock Spire in The Beast's room. The boss you encounter is Lord Valthalak. This boss casts a devastating spell called Shadow Wrath. It is reportedly interruptible but I've yet to observe this. Whenever I've fought him, no cast bars display for Valthalaks himself, however his adds (Phantom Assasins?) correctly display their channel cast bar for Defile. 
**Describe the solution or feature you'd like:**
Is it possible to detect and display Lord Valthalak's casts? Specifically for the Shadow Wrath spell? It would be helpful by giving warning to healers prior to the cast as well as function as an additional visual cue for the melee classes to use their interrupt.

**Comment by wardz** [comment]
Do you happen to know the approximate cast time for the ability? Wowhead just says its an instant cast time.

Is this for normal Classic era or Classic Season of Mastery beta? Not sure if there's any difference in boss abilities from these versions.

**Comment by wardz** [comment]
Could also be a special channeled cast come to think of it. Sometimes they display 0 sec cast time if they have several effects attached to it.

I'll add it to next version just incase. Although the cast bar will probably reset every time Shadow Wrath ticks instead of showing a true channeled cast bar, but atleast this will make interrupting easier i guess.

**Comment by GHuser12** [comment]
thanks again!
