### ISSUE TITLE
[Bug]: Focus Castbar in Black Temple Illidari Council Fight

### ISSUE THREAD

**Issue by vgullotta8** [wardz/ClassicCastbars#64]
### What happened?

I play an elemental shaman and on the Illidari Council fight, I setup a macro to interrupt the heal coming from one of the bosses. I setup all my castbars to all look the same, but for some reason, on this one fight, if I have the mob targeted, the castbar is the correct texture I selected, but on my focus target, it reverts back to the blizzard default castbar. It only seems to do it on this fight, other times I have tested a focus target, it uses the proper texture set in media.

### Is there any errors?

```shell
no errors I have found
```

### Game Version

The Burning Crusade Classic

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

Not sure.

### Any additional info?

I can't really test this fight without my other addons, I think it would be a mess, so I am not sure if it happens without other addons. Any help would be greatly appreciated. I attached 2 screenshots so you can see the difference. One during the Illidari Council fight and one while fishing. There is no difference in settings between these two screenshots, but you can clearly see they are different castbars:

![WoWScrnShot_042222_115024](https://user-images.githubusercontent.com/105075384/167196195-8996a7b9-4a89-4384-9aa7-bc5bb9bc212a.jpg)
![WoWScrnShot_042622_204722](https://user-images.githubusercontent.com/105075384/167196197-58e57c04-8e79-4950-b234-3e538e95791e.jpg)

Thank you for any help you can provide. This is obviously not game-breaking lol, but it would be cool if it would use the prettier version =)

Thanks,
Vinny

**Comment by vgullotta8** [comment]
Also noticed it a few times in Sunwell Plateau where the castbar on my target during the Kalecgos fight will be the default blizzard one instead of the nice pretty one lol

**Comment by wardz** [comment]
Oh weird, not sure why Github did that. I didn't get any notifications from this ticket until now :S

The castbar is different because it's using the uninterruptible shield border, you can try disabling it. The addon learns over time which casts are interruptible or not. I'll look more into the issue after the weekend.

**Comment by vgullotta8** [comment]
yeah I figured it didn't notify you cause of the spam thing, it just took them a few hours and they fixed that for my account, so I figured when I noticed it in SWP, I'd update and it would probably ping you. The one on council that I show in the screenshot above is definitely an interruptible spell, cause that's my job, so maybe it is mis-categorized or blizz did something weird with that spell lol, I am not sure, and it's definitely not a big deal, I just figured I'd mention it, cause I really like how it looks in the top screenshot when everything is working normally =)

**Comment by vgullotta8** [comment]
ahh, I see the uninterruptible shield boarder in the settings, I disabled it on target and focus. We are doing BT tonight, so I'll test it out and let you know if that fixed it tonight or tomorrow. Thanks!

**Comment by wardz** [comment]
I'm guessing it was due to the faulty interruptible thingy? You can also individually change the grey fill color aswell.

I haven't played TBC since season 2, but I found this quote on wowhead about the boss you posted:
"Also, it's important to note that she's almost always affected by either BoP (melee immune) or Spell Warding (spell immune), so it's imperative to have both types of interrupts on her."

Is this still the case? If so that's prob how the addon misconfigured it. I'll try add an check for these auras next release.

**Comment by vgullotta8** [comment]
yeah, it was the uninterruptible thing that was doing it. Looks awesome in all fights now =D
