### ISSUE TITLE
Focus in Classic Era

### ISSUE THREAD

**Issue by Wizeowel** [wardz/ClassicCastbars#80]
Hi Wardz, thank you your addon work :)

Heads up. Focus unittype seems to be re-enabled in Classic Era since v14

At least /focus and /clearfocus work and show a name in a simple unitframe somewhere on the screen. However, no health bar or portrait but that could be because I play with raid frames . I have googled a bit today but no one seems to have discussed it.

If it is intended and Blizz doesn't hotfix it out again, then it would be nice if ClassicCastbars would also work with this unittype.

**Comment by wardz** [comment]
Hey, if you're referencing this when typing /focus: 
<img width="350" alt="Screenshot 2023-09-09 at 13 49 53" src="https://github.com/wardz/ClassicCastbars/assets/10900212/249d7748-47db-42ec-b634-ac5e835009f3">
that's actually already the work by ClassicCastbars ;P

It's a rather hidden feature (focus castbar + targetting with some combat limitations) that only me and my brother mostly used so it's not really advertised on the addon page. (If it weren't so limited i'd make it into a seperate addon. For now you also need a macro "/click FocusCastbar" instead of "/target focus" to do targetting)

I'd love to add full focus support one day but dont think they ever will change the api sadly.

**Comment by Wizeowel** [comment]
Aha! That is sneaky but cool and maybe useful. 

So I presume you can't change focus during combat, because your /click FocusCastbar uses protected functions?

**Comment by wardz** [comment]
yeah basically. You can change focus in combat too see their new castbar, but the /click targetting macro wont update to the new unit until you leave combat.
